2021/04/29 09:14:58 [error] 33#33: *27 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.19.0.1, server: localhost, request: "GET /twig HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 09:15:34 [error] 33#33: *27 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.19.0.1, server: localhost, request: "GET /twig HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:04:59 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /twig-example/tags HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:00 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /twig-example/tags HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:06 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /twig-example/tags HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:09 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /twig-example/tags HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:10 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /twig-example/tags HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:11 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /twig-example/tags HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:14 [error] 32#32: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:19 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:20 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:21 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:21 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:22 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:24 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:25 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:25 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:26 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/04/29 22:05:26 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
